version: "3"
services:
  vault:
    image: hashicorp/vault
    restart: unless-stopped
    ports:
      - 8200:8200
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "1234567890"
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: "1234567890"