name: GitLab Mirror
run-name: Synching GitLab Repo
on:
    push:
        branches:
            - 'main'
jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: Check out Repository
              uses: actions/checkout@v3

            - name: Sync GitLab Repo
              uses: adambirds/sync-github-to-gitlab-action@v1.1.0
              with:
                destination_repository: git@gitlab.com:N8BWert/mirror_test.git
                destination_branch_name: main
                destination_ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
