name: GitLab Mirror
run-name: Synching GitLab Repo
on:
    push:
        branches:
            - 'main'
jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: Check out Repository
              uses: actions/checkout@v3

            - name: Sync GitLab Repo
              run: |
                git remote add gitlab https://gitlab.com/N8BWert/mirror_test
                git fetch gitlab
                git push origin main:gitlab/main
