name: GitLab Mirror
run-name: Synching GitLab Repo
on:
    push:
        branches:
            - 'main'
jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: Check out Repository
              uses: actions/checkout@v3

            - name: Sync GitLab Repo
              uses: wangchucheng/git-repo-sync@v0.1.0
              with:
                target-url: https://gitlab.com/N8BWert/mirror_test.git
                target-username: N8BWert
                target-token: ${{ secrets.GITLAB_TOKEN }}
