name: GitLab Mirror
run-name: Synching GitLab Repo
on:
    push:
        branches:
            - 'main'
jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: Check out Repository
              uses: actions/checkout@v3

            - name: Sync GitLab Repo
              uses: SvanBoxel/gitlab-mirror-and-ci-action@master
              with:
                args: "https://gitlab.com/N8BWert/ghreleases.git"
              env:
                FOLLOW_TAGS: "false"
                FORCE_PUSH: "true"
                GITLAB_HOSTNAME: "gitlab.com"
                GITLAB_USERNAME: "N8BWert"
                GITLAB_PASSWORD: ${{ secrets.GITLAB_TOKEN }}
                GITLAB_PROJECT_ID: "48255930"
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
