name: GitLab Mirror
run-name: Synching GitLab Repo
on:
    push:
        branches:
            - 'main'
jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: Check out Repository
              uses: actions/checkout@v3

            - name: Sync GitLab Repo
              uses: net-engine/github-repository-sync-action@v1
              with:
                ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
                target_repo_url: 'git@gitlab.com:N8BWert/mirror_test.git'