name: Release
run-name: Create Release For GHactions
on:
    push:
        tags:
            '[0-9].[0-9].[0-9]'
jobs:
    create-release:
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
            - name: Create Changelog
              uses: heinrichreimer/github-changelog-generator-action@v2.3
              id: Changelog
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
            - name: Create random artifacts
              run: |
                mkdir downloads && cd downloads
                echo 'alpha' > alpha.txt
                cd ..
            - name: Upload Artifacts
              uses: softprops/action-gh-release@v1
              with:
                tag_name: ${{ github.ref }}
                name: Release ${{ github.ref }}
                body: |
                    ${{ steps.Changelog.outputs.changelog }}
                draft: false
                prerelease: false
                files: |
                  downloads/alpha.txt
            # - name: Create Release
            #   id: create_release
            #   uses: actions/create-release@latest
            #   env:
            #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            #   with:
            #     tag_name: ${{ github.ref }}
            #     release_name: Release ${{ github.ref }}
            #     body: |
            #         ${{ steps.Changelog.outputs.changelog }}
            #     draft: false
            #     prerelease: false
